# <u>i</u>  Preface {-}

<br>

::: {.body-text width="100%"}
Whatever way we choose to look at it, or words we might choose to describe it, it is a global truth that the health of people is inseparably linked to that of their environment. 

There are fewer places where this foundational relationship is more apparent, and tested, than along our coastlines and estuarine waterways. Long having been magnets for human settlements given their vast productivity, access, travel routes and safe harbour, these environments have distilled over time the collective impacts of human development, modification and dependency for resources, livelihoods and lifestyles. And given their location on the frontline of many of the environmental shifts under climate change, our coastal environments also amplify the risks and transitions that come with rising sea levels, less rainfall and warmer temperatures, among other impacts. Invariably then, the most important question is how we maintain diverse and productive coastal ecosystems to help sustain our coastal communities in the face of escalating population growth and climate stressors. This question is particularly pertinent in the Australian context, given that more than 80% of our population lives within 50 km of the coast and is mainly concentrated within the catchments of large shallow estuaries situated on low-elevation coastlines. For the large part, we have built our culture, our identity and our way of life on our coasts and estuaries, and finding ways to sustain and most importantly adapt to these transitioning environments is key to our longevity. 

The central thesis of this book aims to advance understanding of this fundamental question, working within the context of the largest estuarine system in south-western Australia, the Peel-Harvey. For reasons outlined in the following chapters, there are many reasons why this vast catchment-estuarine system makes an excellent case study for this purpose.

The work we have collated here grew from a desire to understand more about the linkages that drive an estuarine-catchment system, originally from an environmental-ecological perspective which then evolved to include another fundamental component of the ecosystem – it’s people. Through making and modelling those links, conceptually then quantitatively, our intent became one of how we might get better at forecasting potential futures and what we could do differently now to steer towards a future we want, rather than staying a on a path we got better at understanding but did too little about.

To this end, the following document, which embodies a series of interconnected yet stand-alone studies as individual chapters, has been organised into the following sections that represent our journey throughout this three-year research project. Following an overarching synthesis, the first section on Characterising the Environment unpacks the development of a sophisticated catchment-estuary model and the data, existing and new, needed to build and validate this central framework. From the depths of the estuarine sediment to the dynamics and chemistry of its overlying water - including tracing the catchment origins, pathways and destination of nutrients in the receiving estuary - we spent considerable time and effort attempting to recreate the complex environmental functioning of the Peel-Harvey, both for the present and over its checkered history since the 1970s. The section on Estuarine Ecological Health then delves into fundamental ecological components from the benthic to pelagic, spanning in-depth studies from the 1970s to the present on the Peel-Harvey’s seagrass and macroalgal communities, benthic infauna and fish fauna. Importantly, these ecological studies endeavored to not simply report changes in community composition over space and time, but to synthesise key signals of their structural and functional health into simple ‘report-card’ grades that were then linked to environmental drivers. The Economic Health section focused on building an economic model for the Peel-Harvey and characterizing the ability of the region to create jobs locally and specialise economically. And finally, we sought in the Decision Support System and 2050 Scenarios section to integrate all of the above into a predictive framework for exploring the consequences on both ecological and economic resilience of particular catchment development and management decisions, both under current climate conditions and those anticipated for the region in 2050. Our local partners and stakeholders crafted the future scenarios they most wanted to understand for this vast ecosystem as we developed this final part of our research.

This ambitious project certainly challenged us along the way. The diversity of disciplines and sectors it encompassed brought rich perspectives and vast capability, but also language barriers and ideological differences that needed to be navigated towards common ground. Data richness in some areas belied patchy or non-existent data in others, leading to innovations to sensibly deal with these data gaps or compromises where solutions could not be found. And more broadly, the difficulty of using data snapshots to capture enough of the complexity of these environments to reliably model their socio-ecological functions has since driven new innovations in other systems beyond this project, but which have borrowed heavily from the work we developed here.

Finally, this collation of inter-linked studies is not intended as a finished product – rather, it’s a framework to keep building on and refining over time as more data streams and areas of interest develop. We have, however, significantly advanced the understanding – and practice – of the linkages we set out to make for the Peel-Harvey and other catchment-estuarine ecosystems facing similar challenges and opportunities, now and into our coastal futures.
:::

<br>


# <u>ii</u>  Editors Note {-}

<br>

::: {.body-text width="100%"}
The information, findings and conclusions provided in the following document were derived from a research project undertaken between 2016 and 2019, and are intended to be representative of the relevant data, manager and stakeholder interests and local conditions at that time. We acknowledge that various other initiatives relevant to the estuarine and societal health of the Peel-Harvey have subsequently been developed or implemented, however we have not attempted to represent them in the following collation of research findings.

:::

